### create

POST http://localhost:8000/user/register
Content-Type: application/json

{
        "username": "Dharmesh",
        "email": "dharmesh@gmail.com",
        "password": "123"
}

### 

POST  http://localhost:8000/user/signin
Content-Type: application/json

{
        "email": "dharmesh@gmail.com",
        "password": "123"
}

###

GET http://localhost:8000/user/who